"""Install and remove the systemd unit.

This exists as a Python module rather than only as ``install.sh`` so that the
two supported installs converge on the same end state. ``pipx install`` puts a
CLI on your PATH and nothing else; without this, becoming a service required
cloning the repo for a shell script, so the packaged install and the cloned
install produced different results and could drift apart. ``install.sh`` is now
a thin shim over this module, which makes one implementation authoritative.

The generated unit is sandboxed hard, and one consequence is easy to trip over:
``ProtectHome=yes`` makes ``/home``, ``/root`` and ``/run/user`` inaccessible to
the service, so an ``ExecStart`` under any of them fails with 203/EXEC while
running perfectly from a shell. :func:`locate_binary` refuses that case rather
than writing a unit that cannot start.
"""

from __future__ import annotations

import datetime
import grp
import os
import pwd
import shutil
import subprocess
import sys
from typing import List, Optional

SERVICE_NAME = "firewalla-snmp-proxy"
CONFIG_DIR = "/etc/%s" % SERVICE_NAME
CONFIG_FILE = "%s/config.yaml" % CONFIG_DIR
ENV_FILE = "%s/env" % CONFIG_DIR
STATE_DIR = "/var/lib/%s" % SERVICE_NAME
UNIT_FILE = "/etc/systemd/system/%s.service" % SERVICE_NAME
MIB_DIR = "/usr/share/snmp/mibs"
MIB_NAME = "FIREWALLA-SNMP-PROXY-MIB.txt"

#: Directories the unit's ProtectHome=yes makes unreachable.
FORBIDDEN_EXEC_PREFIXES = ("/home/", "/root/")

ENV_TEMPLATE = """\
# Environment for firewalla-snmp-proxy.
# Put your Firewalla MSP API token here. This file is mode 0640, root-owned,
# readable only by the service group.
FIREWALLA_MSP_TOKEN=
"""

UNIT_TEMPLATE = """\
# Generated by {name} on {when}
# Regenerate with: sudo {name} install-service
[Unit]
Description=Firewalla Switch SNMP proxy
Documentation=https://github.com/kdesch5000/firewalla-snmp-proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={user}
Group={user}
EnvironmentFile={env_file}
ExecStart={binary} run --config {config_file}
Restart=on-failure
RestartSec=15s

# The proxy only needs outbound HTTPS and its own UDP listeners, so it can be
# locked down hard.
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_INET AF_INET6
RestrictNamespaces=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
RestrictRealtime=yes
# The one writable path: the counter state and topology cache.
ReadWritePaths={state_dir}

# Default listen ports are >1024, so no privileged-port capability is needed.
CapabilityBoundingSet=
AmbientCapabilities=

[Install]
WantedBy=multi-user.target
"""


class ServiceError(Exception):
    """Anything that should stop the install with a readable message."""


def _say(msg: str) -> None:
    print("==> %s" % msg)


def _warn(msg: str) -> None:
    print("warning: %s" % msg, file=sys.stderr)


def require_root() -> None:
    if os.geteuid() != 0:
        raise ServiceError("must run as root (use sudo)")


def locate_binary(explicit: Optional[str] = None) -> str:
    """Absolute path to the installed console script.

    ``sys.argv[0]`` is not used: under ``sudo`` it can be a relative path, and
    when invoked via ``python -m`` it is not a console script at all.
    """
    if explicit:
        path = os.path.abspath(explicit)
        if not os.access(path, os.X_OK):
            raise ServiceError("%s is not executable" % path)
        return _check_exec_path(path)

    candidates: List[str] = [
        "/usr/local/bin/%s" % SERVICE_NAME,
        "/usr/bin/%s" % SERVICE_NAME,
        os.path.join(os.path.dirname(os.path.abspath(sys.executable)), SERVICE_NAME),
    ]
    found = shutil.which(SERVICE_NAME)
    if found:
        candidates.append(found)

    for cand in candidates:
        if cand and os.access(cand, os.X_OK):
            return _check_exec_path(cand)

    raise ServiceError(
        "cannot find the '%s' executable.\n\n"
        "Install it system-wide first:\n\n"
        "    sudo pipx --global install %s\n" % (SERVICE_NAME, SERVICE_NAME)
    )


def _check_exec_path(path: str) -> str:
    for prefix in FORBIDDEN_EXEC_PREFIXES:
        if path.startswith(prefix):
            raise ServiceError(
                "the executable is at %s, inside a home directory.\n\n"
                "The service sandbox sets ProtectHome=yes, so systemd cannot "
                "execute anything under /home or /root -- the unit would fail "
                "with status 203/EXEC even though the binary works fine from "
                "your shell.\n\n"
                "Install it system-wide instead, then re-run this:\n\n"
                "    pipx uninstall %s          # as the user who installed it\n"
                "    sudo pipx --global install %s\n\n"
                "That puts it in /usr/local/bin, which the sandbox can reach."
                % (path, SERVICE_NAME, SERVICE_NAME)
            )
    return path


def _systemctl(*args: str, check: bool = True) -> int:
    proc = subprocess.run(["systemctl", *args])
    if check and proc.returncode != 0:
        raise ServiceError("systemctl %s failed" % " ".join(args))
    return proc.returncode


def ensure_user(user: str) -> None:
    try:
        pwd.getpwnam(user)
        _say("Service user %s already exists" % user)
        return
    except KeyError:
        pass
    _say("Creating system user %s" % user)
    subprocess.run(
        ["useradd", "--system", "--no-create-home",
         "--shell", "/usr/sbin/nologin", user],
        check=True,
    )


def _chown(path: str, user: Optional[str], group: str) -> None:
    uid = pwd.getpwnam(user).pw_uid if user else -1
    os.chown(path, uid, grp.getgrnam(group).gr_gid)


def find_mib() -> Optional[str]:
    """The vendor MIB, whether we are a wheel install or a repo checkout.

    Both put it one level above the package directory -- ``site-packages/mibs``
    for a wheel, ``<repo>/mibs`` for a checkout -- so one relative path covers
    both.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    for cand in (
        os.path.join(os.path.dirname(here), "mibs", MIB_NAME),
        os.path.join(os.getcwd(), "mibs", MIB_NAME),
    ):
        if os.path.isfile(cand):
            return cand
    return None


def config_is_ready() -> bool:
    """True when there is both a config and a non-empty token to start with."""
    if not os.path.isfile(CONFIG_FILE):
        return False
    try:
        with open(ENV_FILE, "r", encoding="utf-8") as fh:
            for line in fh:
                if line.startswith("FIREWALLA_MSP_TOKEN=") and line.split("=", 1)[1].strip():
                    return True
    except OSError:
        return False
    return False


def install(user: str = SERVICE_NAME, binary: Optional[str] = None,
            start: bool = True) -> int:
    require_root()
    bin_path = locate_binary(binary)
    _say("Using executable: %s" % bin_path)

    ensure_user(user)

    os.makedirs(CONFIG_DIR, exist_ok=True)
    os.chmod(CONFIG_DIR, 0o750)
    _chown(CONFIG_DIR, "root", user)

    os.makedirs(STATE_DIR, exist_ok=True)
    os.chmod(STATE_DIR, 0o750)
    _chown(STATE_DIR, user, user)

    if not os.path.exists(ENV_FILE):
        with open(ENV_FILE, "w", encoding="utf-8") as fh:
            fh.write(ENV_TEMPLATE)
        _warn("Add your API token to %s" % ENV_FILE)
    else:
        _say("Keeping existing %s" % ENV_FILE)
    os.chmod(ENV_FILE, 0o640)
    _chown(ENV_FILE, "root", user)

    if os.path.exists(CONFIG_FILE):
        _say("Keeping existing %s" % CONFIG_FILE)
        os.chmod(CONFIG_FILE, 0o640)
        _chown(CONFIG_FILE, "root", user)
    else:
        _warn("No config at %s yet -- create one with '%s init'."
              % (CONFIG_FILE, SERVICE_NAME))

    mib = find_mib()
    if mib:
        os.makedirs(MIB_DIR, exist_ok=True)
        shutil.copyfile(mib, os.path.join(MIB_DIR, MIB_NAME))
        os.chmod(os.path.join(MIB_DIR, MIB_NAME), 0o644)
        _say("Installed MIB to %s/%s" % (MIB_DIR, MIB_NAME))

    _say("Writing %s" % UNIT_FILE)
    with open(UNIT_FILE, "w", encoding="utf-8") as fh:
        fh.write(UNIT_TEMPLATE.format(
            name=SERVICE_NAME,
            when=datetime.datetime.now().isoformat(timespec="seconds"),
            user=user,
            env_file=ENV_FILE,
            binary=bin_path,
            config_file=CONFIG_FILE,
            state_dir=STATE_DIR,
        ))
    os.chmod(UNIT_FILE, 0o644)
    _systemctl("daemon-reload")

    # Enable unconditionally: surviving a reboot is the whole point, and it
    # costs nothing when the config is not ready yet.
    _systemctl("enable", SERVICE_NAME)
    _say("Enabled at boot.")

    if start and config_is_ready():
        _systemctl("restart", SERVICE_NAME)
        _say("Started. Follow it with: journalctl -u %s -f" % SERVICE_NAME)
    else:
        print()
        _say("Not started yet -- finish these, then 'systemctl start %s':" % SERVICE_NAME)
        print()
        print("  1. Put your API token in:  %s" % ENV_FILE)
        print("  2. Generate a config:")
        print("       export FIREWALLA_MSP_TOKEN=<token>")
        print("       %s init --domain <your>.firewalla.net -o %s --force"
              % (SERVICE_NAME, CONFIG_FILE))
        print("  3. Validate it:            %s check -c %s" % (SERVICE_NAME, CONFIG_FILE))
        print("  4. Start it:               systemctl start %s" % SERVICE_NAME)
        print("  5. Watch it:               journalctl -u %s -f" % SERVICE_NAME)
        print()
    return 0


def uninstall(purge: bool = False) -> int:
    require_root()
    _say("Stopping and disabling %s" % SERVICE_NAME)
    _systemctl("disable", "--now", SERVICE_NAME, check=False)
    if os.path.exists(UNIT_FILE):
        os.unlink(UNIT_FILE)
    _systemctl("daemon-reload", check=False)
    _say("Removed the unit file.")

    if purge:
        for path in (CONFIG_DIR, STATE_DIR):
            shutil.rmtree(path, ignore_errors=True)
        _say("Removed %s and %s" % (CONFIG_DIR, STATE_DIR))
        _warn("Your MSP API token is gone from this host, but is still valid. "
              "Delete it in the MSP console if you are done with it.")
    else:
        # Not removed by default: the config holds your token, and discarding
        # the counter offsets causes one spurious spike on a reinstall.
        _say("Left in place: %s and %s" % (CONFIG_DIR, STATE_DIR))
        _say("  Remove them too with: sudo %s uninstall-service --purge" % SERVICE_NAME)
    return 0
